
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:  jdbc:mariadb://localhost:3306/test
    username: javaroot
    password: rootpassword
    
  messages:
    fallback-to-system-locale: false
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none

logging:
  file:
    name: logs/spring-boot.log
  level:
    org:
      springframework:
        jdbc:
          core : TRACE
          